[package]
name = "cpe_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.9.0", features = ["macros"] }
sqlx = { version = "0.8.2", features = ["mysql", "runtime-tokio-native-tls"] }
dotenv = "0.15"